<?php
function viewsremovedupes_views_pre_render(&$view)
{
  $used_nids = array();
  if ($view->name == 'regenannouncementcarousel')
  {
      foreach ($view->result as $row)
      {
        if (!in_array($row->nid, $used_nids))
        {
          $new_view_result[] = $row;
          $used_nids[] = $row->nid;
        }
      }
   
      $view->result = $new_view_result;
  }
}

function viewsremovedupes_views_query_alter(&$view, &$query) {
}

?>
